print("Python journey begins")
print("Hi my name is Abhiraaj, I am starting my Python and Git journey")
print("For adding my files to Git tracking I am using git add . command")
print("For commiting my file changes to Git I am using git commit -m '''commit message''' command")
print("To make sure no other person has updated the branch I am using git pull origin <branch name> command to fetch updated changes if any")
print("For pusing my commited chnages to Git I am using git push origin <branch name> command")